# Generated by Django 5.1.3 on 2024-12-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='avarage_rate',
            new_name='average_rate',
        ),
    ]
